# This configuration requires Tesla V100-SXM2(32GB) x 8 GPUs It takes about 4 days.
batch_type: length
batch_bins: 160000
accum_grad: 4
max_epoch: 10 

patience: none
init: xavier_uniform 

best_model_criterion:
-   - valid
    - acc
    - max

val_scheduler_criterion:
- valid
- acc

keep_nbest_models: 10
log_interval: 10


preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 1024
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d8
    normalize_before: false
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 512
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.15
    length_normalized_loss: false
    extract_feats_in_collect_stats: false

optim: adam
optim_conf:
    lr: 0.001

scheduler: warmuplr
scheduler_conf: 
    warmup_steps: 50

input_size: null

ctc_conf:
        ignore_nan_grad: true

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hubert_large_ll60k  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: True
    extracted_feature: True
    max_seq_len: 20000

normalize: null

#unused_parameters: True 
specaug: null
