# This configuration requires TITAN RTX (12GB) x 4 GPUs It takes about XX days.
batch_type: numel
batch_bins: 80000000
accum_grad: 1
max_epoch: 80
patience: 15

input_size: 83

init: none
val_scheduler_criterion:
    - valid
    - acc
early_stopping_criterion:
    - valid
    - acc
    - max
best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - wer
    - min
    
keep_nbest_models: 10
log_interval: 1200
encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    use_video: True
    video_upsample_mode: "attention"
    video_fusion_type: vat

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
    use_video: true
    video_hierarchical_attn: true
    video_dim: 2048

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.15
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.001
scheduler: reducelronplateau
scheduler_conf:
        factor: 0.85
        mode: max
        patience: 3

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
